version: "3.7"

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.volumes/postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: ./Dockerfile.api
    container_name: api
    restart: always
    environment:
      - JWT_SECRET=535f6cd72079e2d7eee8251816977b14c0623e3814fecfe1803b7a9c2f498565
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MINIO_ENDPOINT=minio:9000
      - MINIO_BUCKET=tagmate
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - 8000:8000
    # uncomment the volume mapping if hot reload is required
    volumes:
      - ./tagmate:/applications/tagmate
    depends_on:
      - postgres
      - redis
      - minio

  worker:
    build:
      context: .
      dockerfile: ./Dockerfile.worker
    container_name: worker
    restart: always
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MINIO_ENDPOINT=minio:9000
      - MINIO_BUCKET=tagmate
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./.volumes/worker/cache:/root/.cache
    depends_on:
      - postgres
      - redis
      - minio

  minio:
    image: minio/minio
    container_name: minio
    command: minio server /data --console-address ":9001"
    restart: always
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./.volumes/minio:/data


networks:
  tagmate:
    driver: bridge
    name: tagmate
